[package]
name = "kumono"
version = "0.2.0"
edition.workspace = true
description.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
strum_macros = "0.27.*"

# [dev-dependencies]